% Read a graph generated by the `krongen' generator
% in the SNAP library. (Make sure you remove the comments
% inside the target file first)

function [A] = readsnap(fname)
  A = load(fname);
  A = A + 1;
  A(:,3) = 1;
  A = spconvert(A);
  m = max(size(A));
  A(m,m)=1; %this makes sure A is square... but should just use a resize function
end
