% Read a graph generated by the `krongen' generator
% in the SNAP library. (Make sure you remove the comments
% inside the target file first)

function [A] = readsnap(fname)
  A = load(fname);
  A = A + 1;
  A(:,3) = 1;
  A = spconvert(A);
  m = max(size(A));
  if (size(A,1) != size(A,2))
    A(m,m)=0;
  end
end
